#
name: portfolio-frontend-charley
namespace: charley

replicaCount: 1

image:
  repository: lamenace90/portfolio-frontend
  pullPolicy: Always
  tag: 'e11be28'

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
